language: python
python: 
  - '3.8.3'
  - '3.7.7'
  - '3.6.10'
cache: pip
before_install:
  - python --version
  - python -m pip install --upgrade pip
  - pip install black pytest pytest-xdist --upgrade
install:
  - python setup.py install_egg_info
  - pip install -e . ".[full]"
  - pip freeze # print all pip packages & versions
script:
  - black . --check
  - echo "import textattack" | python # run textattack post-install hooks
  - travis_wait 30 pytest tests -vx --dist=loadfile -n auto
